# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b6c5840ca3f52df57f74021d6d8a1a600da6f2d531c15cbe01144b1c5b0dbcbb534d9f8c981722a45127c63c3c385024c97548c34e3b57e38187319fc1f7dea

test:
  secret_key_base: db8f419f82c43df75551f23dbaa537bf998ecf54c3c80922bd4e3423780fa2e858c3ea55a0101ba82d1919e29fd21265c174e7c1353ab3b1ac703b39113da227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
